package com.example.gameProject.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Represents the CreatureType entity in the game project.
 * Each creature type has a name, description, health modifier, and attack modifier.
 * This entity will be stored in the database using the table generated by Hibernate.
 */
@Entity
public class CreatureType {

    // Primary key for CreatureType, auto-generated.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Name of the creature type.
    private String name;

    // Description of the creature type, explaining its attributes or role.
    private String description;

    // Modifier applied to a creature's health based on its type.
    private double healthModifier;

    // Modifier applied to a creature's attack based on its type.
    private double attackModifier;

    // Timestamp of when the creature type was created.
    private LocalDateTime createdAt;

    // Default constructor required by JPA.
    public CreatureType() {}

    /**
     * Constructor for creating a new CreatureType with the specified attributes.
     * @param name Name of the creature type.
     * @param description Description of the creature type.
     * @param healthModifier Health modifier for this type.
     * @param attackModifier Attack modifier for this type.
     */
    public CreatureType(String name, String description, double healthModifier, double attackModifier) {
        this.name = name;
        this.description = description;
        this.healthModifier = healthModifier;
        this.attackModifier = attackModifier;
        this.createdAt = LocalDateTime.now();  // Sets the creation time to the current time.
    }

    // Getters and setters for all fields.
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getHealthModifier() {
        return healthModifier;
    }

    public void setHealthModifier(double healthModifier) {
        this.healthModifier = healthModifier;
    }

    public double getAttackModifier() {
        return attackModifier;
    }

    public void setAttackModifier(double attackModifier) {
        this.attackModifier = attackModifier;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
